/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amodtech_colabandroid_CompressionActivity */

#ifndef _Included_com_amodtech_colabandroid_CompressionActivity
#define _Included_com_amodtech_colabandroid_CompressionActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amodtech_colabandroid_CompressionActivity_MODE_PRIVATE
#define com_amodtech_colabandroid_CompressionActivity_MODE_PRIVATE 0L
#undef com_amodtech_colabandroid_CompressionActivity_MODE_WORLD_READABLE
#define com_amodtech_colabandroid_CompressionActivity_MODE_WORLD_READABLE 1L
#undef com_amodtech_colabandroid_CompressionActivity_MODE_WORLD_WRITEABLE
#define com_amodtech_colabandroid_CompressionActivity_MODE_WORLD_WRITEABLE 2L
#undef com_amodtech_colabandroid_CompressionActivity_MODE_APPEND
#define com_amodtech_colabandroid_CompressionActivity_MODE_APPEND 32768L
#undef com_amodtech_colabandroid_CompressionActivity_MODE_MULTI_PROCESS
#define com_amodtech_colabandroid_CompressionActivity_MODE_MULTI_PROCESS 4L
#undef com_amodtech_colabandroid_CompressionActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_amodtech_colabandroid_CompressionActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_AUTO_CREATE
#define com_amodtech_colabandroid_CompressionActivity_BIND_AUTO_CREATE 1L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_DEBUG_UNBIND
#define com_amodtech_colabandroid_CompressionActivity_BIND_DEBUG_UNBIND 2L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_NOT_FOREGROUND
#define com_amodtech_colabandroid_CompressionActivity_BIND_NOT_FOREGROUND 4L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_ABOVE_CLIENT
#define com_amodtech_colabandroid_CompressionActivity_BIND_ABOVE_CLIENT 8L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_amodtech_colabandroid_CompressionActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_WAIVE_PRIORITY
#define com_amodtech_colabandroid_CompressionActivity_BIND_WAIVE_PRIORITY 32L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_IMPORTANT
#define com_amodtech_colabandroid_CompressionActivity_BIND_IMPORTANT 64L
#undef com_amodtech_colabandroid_CompressionActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_amodtech_colabandroid_CompressionActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_amodtech_colabandroid_CompressionActivity_CONTEXT_INCLUDE_CODE
#define com_amodtech_colabandroid_CompressionActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_amodtech_colabandroid_CompressionActivity_CONTEXT_IGNORE_SECURITY
#define com_amodtech_colabandroid_CompressionActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_amodtech_colabandroid_CompressionActivity_CONTEXT_RESTRICTED
#define com_amodtech_colabandroid_CompressionActivity_CONTEXT_RESTRICTED 4L
#undef com_amodtech_colabandroid_CompressionActivity_RESULT_CANCELED
#define com_amodtech_colabandroid_CompressionActivity_RESULT_CANCELED 0L
#undef com_amodtech_colabandroid_CompressionActivity_RESULT_OK
#define com_amodtech_colabandroid_CompressionActivity_RESULT_OK -1L
#undef com_amodtech_colabandroid_CompressionActivity_RESULT_FIRST_USER
#define com_amodtech_colabandroid_CompressionActivity_RESULT_FIRST_USER 1L
#undef com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_DISABLE
#define com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_DIALER
#define com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_DIALER 1L
#undef com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SHORTCUT
#define com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_amodtech_colabandroid_CompressionActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amodtech_colabandroid_CompressionActivity_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    naInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_CompressionActivity_naInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_amodtech_colabandroid_CompressionActivity_naGetVideoRes
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    naFinish
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_CompressionActivity_naFinish
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    naGetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_CompressionActivity_naGetDuration
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    naGetFrameRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_CompressionActivity_naGetFrameRate
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_CompressionActivity
 * Method:    ffmpegWrapper
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_CompressionActivity_ffmpegWrapper
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
