/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amodtech_colabandroid_FfmpegJNIWrapper */

#ifndef _Included_com_amodtech_colabandroid_FfmpegJNIWrapper
#define _Included_com_amodtech_colabandroid_FfmpegJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    naInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_naInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_naGetVideoRes
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    naFinish
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_naFinish
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    naGetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_naGetDuration
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    naGetFrameRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_naGetFrameRate
  (JNIEnv *, jclass);

/*
 * Class:     com_amodtech_colabandroid_FfmpegJNIWrapper
 * Method:    ffmpegWrapper
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_colabandroid_FfmpegJNIWrapper_ffmpegWrapper
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
